export {
  buildCommandCenterSummary,
  buildPipelineOverview,
  buildCityOptions,
  buildProspectInsight,
  buildProspectRecords,
  buildSectorOptions,
  buildTodayBuckets,
  filterByBounds,
  getOpportunityTier,
  normalizeRankingFilters,
  OPPORTUNITY_META,
  sortProspectRecordsByScore,
} from "@/lib/commercial/engine";
export { buildConquestSnapshot } from "@/lib/commercial/territory";
export { buildOpportunityAlerts } from "@/lib/commercial/alerts";
export {
  ATTACK_RESULT_OPTIONS,
  DEFAULT_ATTACK_FILTERS,
  DEFAULT_ATTACK_RESULT_DRAFT,
  buildAttackNextStepSuggestion,
  buildAttackQueue,
  buildAttackSessionFiltersSnapshot,
  buildAttackSessionKpis,
  buildAttackSessionProgress,
  buildBusinessUpdateFromAttackResult,
  buildDefaultAttackSessionName,
  getCurrentAttackLead,
} from "@/lib/commercial/attack";

export {
  buildDefaultCommercialSettings,
  DEFAULT_COMMERCIAL_PREFERENCES,
  DEFAULT_SCORING_CONFIG,
  getVerticalConfig,
  getVerticalLabel,
  SCORING_RULES_META,
  SERVICE_META,
  VERTICAL_CONFIGS,
} from "@/lib/commercial/verticals";

export { parseAccountSettingsRow } from "@/lib/commercial/account-settings";
export {
  applyKnowledgeSummaryToProfile,
  buildDefaultAccountCommercialProfile,
  extractKnowledgeSummaryFromText,
  isAccountCommercialProfileComplete,
  parseAccountCommercialProfileRow,
  readAccountCommercialProfileFromStorage,
  sanitizeAccountCommercialProfile,
  toAccountCommercialProfileUpsert,
  writeAccountCommercialProfileToStorage,
} from "@/lib/commercial/account-profile";

export type {
  AttackItemStatus,
  AttackNextStepSuggestion,
  AttackQueueEntry,
  AttackQueueFilters,
  AttackResultDraft,
  AttackResultKind,
  AttackResultOption,
  AttackSessionFiltersSnapshot,
  AttackSessionKpis,
  AttackSessionProgress,
  AttackSessionSource,
  AttackSessionStatus,
  AccountCommercialProfile,
  AccountCommercialSettings,
  AccountKnowledgeSummary,
  CommercialPreferences,
  CommandCenterSummary,
  ConquestSnapshot,
  ConquestZoneSummary,
  DemoBadge,
  IdealCustomerProfile,
  ObjectionResponse,
  OfferProfile,
  OpportunityTier,
  OpportunityAlert,
  OpportunityAlertKind,
  OrbitaService,
  PipelineSnapshot,
  PricingProfile,
  ProspectInsight,
  ProspectingPreferencesProfile,
  ProspectRecord,
  ScoreBreakdownItem,
  ScoringConfig,
  ServiceRecommendation,
  TodayBuckets,
  UrgencyLevel,
  VerticalConfig,
  ValueBand,
  VerticalId,
} from "@/lib/commercial/types";
